### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by jancantor** [jessfraz/directory-theme#3]
Hi Jess!

How's it going?

This theme is legit! Can't go back to the default and ugly apache theme.

But here's a minor catch I found. So I recently upgraded to Yosemite and then my localhost stopped working. I get a **500 Internal Service Error** when I load my local server. I couldn't figure out what was causeing this error. First, it thought it might be something in my `httpd.config` or `username.conf`, but nope, that wasn't it. Then I check the `.htaccess` tried commenting from line 68-71, and it worked! The 500 Error went away. so it's all good now.

```
    # RewriteEngine on
    # RewriteCond %{REQUEST_FILENAME} !-d
    # RewriteCond %{REQUEST_FILENAME}\.html -f
    # RewriteRule ^(.*)$ $1.html
```

So yeah, I don't think it's a major issue but I thought I'd share it anway.

**Comment by jessfraz** [comment]
closing as this is archived but thanks and sorry!!!
